//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.12 at 02:12:18 PM WEST 
//


package me.ketlas.microservicemulticonnectors.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the me.ketlas.microservicemulticonnectors.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: me.ketlas.microservicemulticonnectors.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccountsRequest }
     * 
     */
    public AccountsRequest createAccountsRequest() {
        return new AccountsRequest();
    }

    /**
     * Create an instance of {@link AccountsResponse }
     * 
     */
    public AccountsResponse createAccountsResponse() {
        return new AccountsResponse();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link AccountDetailsRequest }
     * 
     */
    public AccountDetailsRequest createAccountDetailsRequest() {
        return new AccountDetailsRequest();
    }

    /**
     * Create an instance of {@link UpdateAccountRequest }
     * 
     */
    public UpdateAccountRequest createUpdateAccountRequest() {
        return new UpdateAccountRequest();
    }

    /**
     * Create an instance of {@link DeleteAccountRequest }
     * 
     */
    public DeleteAccountRequest createDeleteAccountRequest() {
        return new DeleteAccountRequest();
    }

    /**
     * Create an instance of {@link DeleteAccountResponse }
     * 
     */
    public DeleteAccountResponse createDeleteAccountResponse() {
        return new DeleteAccountResponse();
    }

    /**
     * Create an instance of {@link SaveAccountResponse }
     * 
     */
    public SaveAccountResponse createSaveAccountResponse() {
        return new SaveAccountResponse();
    }

    /**
     * Create an instance of {@link SaveAccountRequest }
     * 
     */
    public SaveAccountRequest createSaveAccountRequest() {
        return new SaveAccountRequest();
    }

}
